### ISSUE TITLE
is this now abandoned? 

### ISSUE THREAD

**Issue by JoshuaEdwards1991** [jberta93/ng-facebook-api#7]
could really use the post to facebook update

**Comment by rowild** [comment]
Wondering the same thing... @jberta93 any chance for a comment? Thanks!

**Comment by jberta93** [comment]
Hi, the project isn't abandoned can you explain better what are your needing? Maybe with an example?

**Comment by rowild** [comment]
Hi, thanks for your response! I have an app that support the FB API 2.3, which will be shut down in July. So I need to update. I was wondering, which versions of the FB API you support? Would be great, if you could mention that in the Readme! - Moltissimo grazie! 👍

**Comment by jberta93** [comment]
I guess you to check the Facebook Changelog to verify if you use some apis that in new version are deprecated.

In the login mechanism there isn't any difference between new and older api.

If somethings goes wrong updating the version, feel free to open me an issue.

**Comment by JoshuaEdwards1991** [comment]
It says in your mai page that your are going to support a fb post method, but you haven't done so already. 

I've forked your code and added this functionality, happy to add it to the project if needed

**Comment by jberta93** [comment]
Can you make a pull request?
